# Generated by Django 6.1.1 on 2026-09-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('kind', models.CharField(choices=[('tutors', 'All tutors — one row per tutor'), ('tutor', 'One tutor and their students'), ('student', 'One student'), ('all', 'Everything — all tutors and all students')], max_length=10, verbose_name='report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['email', 'kind'],
                'unique_together': {('email', 'kind')},
            },
        ),
    ]
