# Generated by Django 6.1.1 on 2026-09-23 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, help_text='e.g. ESL, GED math', max_length=100)),
                ('site', models.CharField(blank=True, help_text='Tutoring site', max_length=120)),
                ('days', models.CharField(blank=True, help_text='e.g. Mon & Wed', max_length=120)),
                ('times', models.CharField(blank=True, help_text='e.g. 6:00–7:30 pm', max_length=120)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('end_reason', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'A. Economic'), ('B', 'B. Educational'), ('C', 'C. Family'), ('D', 'D. Societal/Community'), ('E', 'E. Other')], max_length=1)),
                ('label', models.CharField(max_length=120)),
                ('federally_reported', models.BooleanField(default=False, help_text='Starred on the paper form')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
                'unique_together': {('category', 'label')},
            },
        ),
        migrations.CreateModel(
            name='GoalAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_on', models.DateField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='tutoring.assignment')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='tutoring.goal')),
            ],
            options={
                'ordering': ['achieved_on'],
                'unique_together': {('assignment', 'goal')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('absence', models.CharField(blank=True, choices=[('TA', 'Tutor absent'), ('SA', 'Student absent'), ('H', 'Holiday')], default='', max_length=2)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tutoring.assignment')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('absence', ''), ('hours__gt', 0), ('hours__isnull', False)), models.Q(('hours__isnull', True), models.Q(('absence', ''), _negated=True)), _connector='OR'), name='session_hours_xor_absence')],
            },
        ),
    ]
